### ISSUE TITLE
Pls help me

### ISSUE THREAD

**Issue by Luke100pro** [almajiro/larafilm-frontend#1]
I've got an "Network Error", and i don't know what to do.

![2019-10-30-203418_1920x1080_scrot](https://user-images.githubusercontent.com/30533306/67892732-a628e280-fb55-11e9-885b-7fb7b55f3871.png)
![2019-10-30-203336_1920x1080_scrot](https://user-images.githubusercontent.com/30533306/67892739-a923d300-fb55-11e9-91ae-a9b780827d4b.png)

**Comment by almajiro** [comment]
I think it means cannot connect to larafilm api.
This project is frontend of larafilm. so you need to setup the larafilm.

Finally, this project is not complete and there are parts that won't work.

Thank You

**Comment by Luke100pro** [comment]
Thanks for your response.

Firstly I setted larafilm api and it hasn't work. After trying to solve the problem (and fail) i discovered that this app can not be setup on arch linux (one web library is missing and there is no replacement). Next day installed debian on mmy old laptop and it worked flawlessly.
